### ISSUE TITLE
Target and/or actual version compatibility not documented

### ISSUE THREAD

**Issue by DealerUplift-DavidJohnston** [peak6/tab_tier#1]
I'd suggest noting your goal for earliest version compatibility.

If you are OK with 9.1+ at this point have you considered making more use of the "format()" function introduced then?

Side note on style - I'd save yourself and the reader some grief and avoid using E'' literals when forming regular expressions.  Omit the E and don't double-up the back-slashes.  Just a couple of pennies from a fairly heavy regexp user.

David J.

**Comment by trifthen** [comment]
I didn't really have a goal on version  compatibility. I did write it post 9.2, however. I'll make a note of it in the README. I've been using concat so long, I didn't even think of the format function, though I don't see any obvious areas where it would be useful in this particular code.

Regarding the E'' strings, I actually vastly prefer them to using double-escapes. I've been writing regexp since I cut my teeth on Perl in 1997, and I actively despise excessive escapes. It's one of the reasons I was so happy when Postgres introduced dollar-quoting for code blocks. Before that, you had to single-quote the entire function, and double escape everything. Awful.

**Comment by DealerUplift-DavidJohnston** [comment]
On Friday, May 20, 2016, Shaun Thomas <notifications@github.com> wrote:

> I didn't really have a goal on version compatibility. I did write it post
> 9.2, however. I'll make a note of it in the README. I've been using concat
> so long, I didn't even think of the format function, though I don't see any
> obvious areas where it would be useful in this particular code.
>
A few spots where you build up dynamic SQL, but not much.

> Regarding the E'' strings, I actually vastly prefer them to using
> double-escapes.
>
I don't follow...the use of E'' strings requires the double escaping.

These are equivalent:

'123' ~ E'\\d'
'123' ~ '\d'

David J.


-- 
David Johnston
Dealer Uplift Services
585-486-9912
davidj@dealeruplift.com



DISCLAIMER: This e-mail is intended only for the addressee(s) named above.
The information contained in this e-mail, and any attachment(s) thereto,
are intended only for the personal and confidential use of the designated
addressee(s). If the reader of this message is not an intended recipient or
an agent responsible for delivering it to an intended recipient, you are
hereby notified that you have received this e-mail in error, and that any
review, retention, dissemination, distribution, or copying of this
information is strictly prohibited, and may be subject to penalties under
the Electronic Communications Privacy Act, 18 U.S.C. Code Section 2510-2521
and other applicable laws. If you have received this communication in
error, please notify the sender immediately by reply e-mail or by telephone
(410-308-0085) and permanently delete this e-mail message and any
accompanying attachment(s). Thank you.

**Comment by trifthen** [comment]
I misread your comment and didn't look at the actual code... doh! Looking again, I have no idea why I was using the E'' strings in the first place. Some of this code was lifted from a partition library I wrote in 2011, but still... It worked, so I didn't think about the internals enough. I may get some time to refactor this, because eww. :)

**Comment by trifthen** [comment]
I've added the notes about requiring 9.1 and above. While I was in there, I also removed the unnecessary E strings.
